# Generated by Django 2.0.3 on 2018-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.DecimalField(decimal_places=2, max_digits=13)),
                ('cgpa', models.DecimalField(decimal_places=4, max_digits=13)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
