# Generated by Django 2.0.3 on 2018-06-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180416_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproject',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed'))},
        ),
    ]
