# Generated by Django 2.0.3 on 2018-06-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180612_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('groupReq', models.CharField(max_length=100)),
            ],
        ),
    ]
